apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: genkey-pipeline
  generateName: genkey-pipeline-
spec:
  pipelineRef:
    name: genkey-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: key-store

