apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: auth-ms-openliberty-image-internal
  spec:
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/--NAMESPACE_TOOL--/auth-ms-openliberty
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: auth-ms-openliberty-image-external
  spec:
    params:
    - name: url
      value: quay.io/--QUAY_USER--/auth-ms-openliberty
    type: image    
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: auth-ms-openliberty-source
  spec:
    params:
    - name: revision
      value: master
    - name: url
      #value: https://github.com/ibm-garage-ref-storefront/auth-ms-spring
      value: https://github.com/ibm-garage-ref-storefront/auth-ms-openliberty
    type: git
kind: List
